.github/workflows/pr.yaml, Makefile, hack/kind-1.26.yaml, hack/kind-1.28.yaml, sonar-project.properties, tests/e2e/helm-success-path/00-install-operator.yaml, tests/e2e/keycloak-selfsigned-certificates/00-install-operator.yaml
Please include a summary of the change and why it is needed.
Fixes # (issue)
=> chore: Migrate from gerrit to github pipelines

.github/workflows/pr.yaml, Makefile, hack/kind-1.26.yaml, hack/kind-1.28.yaml, sonar-project.properties, tests/e2e/helm-success-path/00-install-operator.yaml, tests/e2e/keycloak-selfsigned-certificates/00-install-operator.yaml
Migrate from gerrit to github.
Fixes #49 
=> chore: Migrate from gerrit to github pipelines (#49)

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md
=> chore: Update current development version (#59)

Makefile, README.md, bundle.Dockerfile, bundle/manifests/client-secret-policy-sample_v1_secret.yaml, bundle/manifests/edp-keycloak-operator.clusterserviceversion.yaml, bundle/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml, bundle/manifests/v1.edp.epam.com_clusterkeycloaks.yaml, bundle/manifests/v1.edp.epam.com_keycloakauthflows.yaml, bundle/manifests/v1.edp.epam.com_keycloakclients.yaml, bundle/manifests/v1.edp.epam.com_keycloakclientscopes.yaml, bundle/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml, bundle/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml, bundle/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml, bundle/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml, bundle/manifests/v1.edp.epam.com_keycloakrealmroles.yaml, bundle/manifests/v1.edp.epam.com_keycloakrealms.yaml, bundle/manifests/v1.edp.epam.com_keycloakrealmusers.yaml, bundle/manifests/v1.edp.epam.com_keycloaks.yaml, bundle/metadata/annotations.yaml, config/manager/kustomization.yaml, config/manifests/bases/edp-keycloak-operator.clusterserviceversion.yaml
chore: Generate OperatorHub bundle for v1.21.0 (#59)
Fixes # (issue)
=> chore: Generate OperatorHub bundle for v1.21.0 (#59)

api/v1/keycloakrealmrole_types.go, api/v1alpha1/keycloakrealmrole_types.go, controllers/keycloakrealmrole/keycloakrealmrole_controller.go
Fix KeycloakRealmRole CRs with duplicated statuses.
Fixes #68 
=> fix: KeycloakRealmRole CR duplicated status

deploy-templates/_crd_examples/keycloakauthflow.yaml
=> chore: Add additional examples of Keycloak AuthFlow resource

pull_request_template.md
Updated the Pull Request template to include "Enhancement" as a new change type.
Fixes #17
=> chore: Update Pull Request Template (#17)

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md
=> chore: Update current development version (#102)

api/common/realm.go, api/v1/keycloakclient_types.go, api/v1/keycloakrealmuser_types.go
Fixed behavior when boolean parameters with default values are always 'true'.
Fixes #56 
- Manual testing
=> fix: Boolean parameters with default values are always 'true'

api/v1/keycloakrealm_types.go, api/v1alpha1/clusterkeycloakrealm_types.go, config/crd/bases/v1.edp.epam.com_clusterkeycloakrealms.yaml, config/crd/bases/v1.edp.epam.com_keycloakrealms.yaml, deploy-templates/crds/v1.edp.epam.com_clusterkeycloakrealms.yaml, deploy-templates/crds/v1.edp.epam.com_keycloakrealms.yaml
Add print columns for KeycloakRealm Resources.
Fixes #109 
- Manual testing.
=> feat: Add print columns for KeycloakRealm Resources

CHANGELOG.md, README.md, bundle/manifests/edp-keycloak-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/edp-keycloak-operator.clusterserviceversion.yaml, deploy-templates/Chart.yaml, deploy-templates/README.md, deploy-templates/README.md.gotmpl
=> chore: Update current development version (#123)

CHANGELOG.md, README.md, bundle/manifests/edp-keycloak-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/edp-keycloak-operator.clusterserviceversion.yaml, deploy-templates/Chart.yaml, deploy-templates/README.md, deploy-templates/README.md.gotmpl
=> chore: Update current development version (#132)

CHANGELOG.md, README.md, bundle/manifests/edp-keycloak-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/edp-keycloak-operator.clusterserviceversion.yaml, deploy-templates/Chart.yaml, deploy-templates/README.md, deploy-templates/README.md.gotmpl
=> chore: Update current development version (#146)

README.md, cmd/main.go, deploy-templates/README.md, deploy-templates/templates/deployment.yaml, deploy-templates/values.yaml, internal/controller/helper/controller_helper.go, internal/controller/helper/controller_helper_test.go, internal/controller/keycloakrealmcomponent/keycloakrealmcomponent_controller.go
Make ownerReference in Keycloak resources optional.
Fixes #(issue)
- Manual testing
=> feat: Make ownerReference in Keycloak resources optional (#71)

CHANGELOG.md, README.md, bundle/manifests/edp-keycloak-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/edp-keycloak-operator.clusterserviceversion.yaml, deploy-templates/Chart.yaml, deploy-templates/README.md, deploy-templates/README.md.gotmpl
=> chore: Update current development version (#160)

bundle.Dockerfile, bundle/manifests/edp-keycloak-operator.clusterserviceversion.yaml, bundle/manifests/v1.edp.epam.com_keycloakauthflows.yaml, bundle/manifests/v1.edp.epam.com_keycloakclients.yaml, bundle/manifests/v1.edp.epam.com_keycloakclientscopes.yaml, bundle/manifests/v1.edp.epam.com_keycloakrealmcomponents.yaml, bundle/manifests/v1.edp.epam.com_keycloakrealmgroups.yaml, bundle/manifests/v1.edp.epam.com_keycloakrealmidentityproviders.yaml, bundle/manifests/v1.edp.epam.com_keycloakrealmrolebatches.yaml, bundle/manifests/v1.edp.epam.com_keycloakrealmroles.yaml, bundle/manifests/v1.edp.epam.com_keycloakrealms.yaml, bundle/manifests/v1.edp.epam.com_keycloakrealmusers.yaml, bundle/metadata/annotations.yaml
=> chore: Publish on the OperatorHub (#170)

internal/controller/keycloakrealmuser/keycloakrealmuser_controller_integration_test.go, internal/controller/keycloakrealmuser/terminator.go
Handle not found error when deleting KeycloakRealmUser.
Fixes #(issue)
- Manually
- Integration test
=> fix: Handle not found error when deleting KeycloakRealmUser

CHANGELOG.md, README.md, bundle/manifests/edp-keycloak-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, config/manifests/bases/edp-keycloak-operator.clusterserviceversion.yaml, deploy-templates/Chart.yaml, deploy-templates/README.md, deploy-templates/README.md.gotmpl
=> chore: Update current development version (#185)

internal/controller/clusterkeycloakrealm/chain/factory.go, internal/controller/clusterkeycloakrealm/clusterkeycloakrealm_controller_integration_test.go
Unable to update default browserFlow in master realm.
Fixes #143 
- Manually
- Integration tests
=> fix: Unable to update default browserFlow in master realm

.github/ISSUE_TEMPLATE/bug_report.md, .gitignore, .vscode/launch.json, .vscode/settings.json, CONTRIBUTING.md, Makefile, README.md, docs/development.md
Added development documentation.
Fixes #204
=> chore: Add development documentation

deploy-templates/README.md, deploy-templates/templates/deployment.yaml, deploy-templates/values.yaml
Adds the ability to use a custom docker registry and podLabels for the operator deployment
Fixes #212
=> feat: Add Docker registry and podLabels to helm chart
