pkg/client/keycloak/adapter/gocloak_adapter_user.go

Fixes https://github.com/epam/edp-keycloak-operator/issues/6
When configuring a User with a desired password, either via `spec.password` or `.spec.passwordSecret`, the password cannot be used for login since the UPDATE_PASSWORD required action is always set, regardless of what was specified in `spec.requiredUserActions`. This makes the User CRD unusable for non-interactive logins by machine users (e.g. a User automatically created for a test job) until an admin manually removes the required Action. Logging in interactively via a browser will also clear the login blocking action, however since this will force a password change, the configured password can no longer be used for automatic logins.
This commit sets the "temporary" attribute of the password to false, the previous value of …

[EPMDEDP-12204]: fix: Allow non-interactive login with set password for KeycloakRealmUser

---

.github/workflows/e2e.yaml
.github/workflows/pr.yaml
.github/workflows/release.yaml

The PR removes explicit caching `actions/caching` in workflows because `actions/setup-go@v4` has built-in caching. For more information, visit https://github.com/actions/setup-go#caching-dependency-files-and-build-outputs
The cache added in the commit https://github.com/epam/edp-keycloak-operator/commit/77584cf1459b19a9635a1eb5396949ae139422f0.
Additionally, the PR updates the versions of the actions: `setup-go` to `v5` and `checkout` to `v4`. It also reorders them so that `checkout` comes before `setup-go`.
For consistency with `pr.yaml` and `release.yaml`, this PR introduces `env.GOLANG_VERSION`.
Here is the screenshot of [`build-and-lint` …

chore: Remove explicit caching in workflows (#34)

---

deploy-templates/README.md
deploy-templates/templates/deployment.yaml
deploy-templates/values.yaml

When deployment in many environments the images are provided via a private repository.
Private repository's require imagePullSecrets.
This PR adds imagePullSecrets to the values file of the chart AND uses it to provide the imagePullSecrets to the deployment.
If no secrets are provided (default) the imagePullSecrets is not applied to the deployment.
Fixes # (issue)

feature: Add imagePullSecrets to enable private repository

---

controllers/keycloakclient/keycloakclient_controller.go

Moved the deletion process of the KeycloakClient before any logic that requires client secrets.
This will help avoid errors if the KeycloakClient secret is removed before it and the deletion process gets stuck.
Fixes #62 
Manually.

fix: Error if KeycloakClient secret is deleted before it

---

deploy-templates/templates/deployment.yaml

The current template of imagePullSecrets places the pull secret within the container specification. This is not correct it should be part of the spec.metadata.spec definition.
When run with the imagePullSecrets defined the current implementation fails to apply to k8s as it is an invalid definition.
This PR corrects the imagePullSecrets definition to the correct location in the Deployment template.
No other changes are made
Fixes #73 

bug: move imagePullSecrets to spec.template.spec

---

CHANGELOG.md
deploy-templates/Chart.yaml
deploy-templates/README.md

chore: Update current development version (#76)

---

README.md
build.groovy
bundle.Dockerfile
bundle/manifests/edp-keycloak-operator.clusterserviceversion.yaml
bundle/manifests/v1.edp.epam.com_clusterkeycloakrealms.yaml
bundle/metadata/annotations.yaml
code-review.groovy
config/manager/kustomization.yaml
config/manifests/bases/edp-keycloak-operator.clusterserviceversion.yaml
create-release.groovy
deploy-templates/Chart.yaml
deploy-templates/README.md

chore: Publish update on OperatorHub (#76)

---

api/v1/keycloakrealm_types.go
config/crd/bases/v1.edp.epam.com_keycloakrealms.yaml
controllers/keycloakrealm/chain/realm_settings.go
controllers/keycloakrealm/chain/realm_settings_test.go
deploy-templates/crds/v1.edp.epam.com_keycloakrealms.yaml
docs/api.md
pkg/client/keycloak/adapter/gocloak_adapter_realms.go

Please include a summary of the change and why it is needed.
Fixes #80 

feat: Add displayHTMLName to realm resource

---

api/v1/keycloakauthflow_types.go
config/crd/bases/v1.edp.epam.com_keycloakauthflows.yaml
controllers/keycloakauthflow/keycloakauthflow_controller.go
controllers/keycloakauthflow/keycloakrauthflow_controller_integration_test.go
deploy-templates/crds/v1.edp.epam.com_keycloakauthflows.yaml
docs/api.md
pkg/client/keycloak/adapter/gocloak_adapter_auth_flow.go
pkg/client/keycloak/adapter/gocloak_adapter_auth_flow_test.go

Add childRequirement for KeycloakAuthFlow
Fixes #82 
- Integration tests
- Unit tests

feat: Add childRequirement for KeycloakAuthFlow

---

.github/workflows/release.yaml
README.md
deploy-templates/Chart.yaml
deploy-templates/README.md
deploy-templates/README.md.gotmpl
deploy-templates/values.yaml

Renamed the EDP name matches to KubeRocketCI.
Fixes #91

chore: Update KubeRocketCI names and documentation links (#91)

---

api/v1/keycloakclient_types.go
api/v1/zz_generated.deepcopy.go
config/crd/bases/v1.edp.epam.com_keycloakclients.yaml
controllers/keycloakclient/chain/put_client_scope.go
controllers/keycloakclient/chain/put_client_scope_test.go
deploy-templates/crds/v1.edp.epam.com_keycloakclients.yaml
docs/api.md
pkg/client/keycloak/adapter/gocloak.go
pkg/client/keycloak/adapter/gocloak_adapter_client.go
pkg/client/keycloak/adapter/mocks/gocloak_mock.go
pkg/client/keycloak/keycloak_client.go
pkg/client/keycloak/mocks/client_mock.go

The change adds support for optional client scopes. This is required because it's a common use-case to only add certain claims on explicitly requested scopes.
I couldn't find any issues that requested this feature.
I've built and deployed this in a local kind cluster, and tested by adding clients with both default and optional scopes. Additionally, I've added two unit tests, which might be on the short side coverage wise, but I'll gladly improve on this, if wanted.

Add support for optional client scopes

---

controllers/keycloakrealmgroup/keycloakrealmgroup_controller.go
controllers/keycloakrealmgroup/keycloakrealmgroup_controller_integration_test.go
controllers/keycloakrealmgroup/terminator.go
controllers/keycloakrealmuser/keycloakrealmuser_controller.go

Problem:
If we delete the subgroup before deleting the resources that contain this subgroup
(Example: KeycloakRealmGroup.spec.subGroup/KeycloakRealmUser.spec.groups) deletion of KeycloakRealmGroup/KeycloakRealmUser blocks with an error. This happens because we are syncing KeycloakRealmUser/KeycloakRealmGroup before deletion, and syncing can't be processed without a subgroup. 
Solution:
Moved deletion of KeycloakRealmUser/KeycloakRealmGroup before syncing. We don't need to sync objects that are marked for deletion.
Fixes #95 
- Integration tests
- Manual testing
- [ x I have added tests that prove my fix is effective or that my feature works

fix: Deletion resources related to subgroup

---

api/v1/keycloakrealm_types.go
api/v1alpha1/clusterkeycloakrealm_types.go
config/crd/bases/v1.edp.epam.com_clusterkeycloakrealms.yaml
config/crd/bases/v1.edp.epam.com_keycloakrealms.yaml
controllers/clusterkeycloakrealm/chain/put_realm_settings.go
controllers/clusterkeycloakrealm/clusterkeycloakrealm_controller_integration_test.go
controllers/keycloakrealm/chain/chain_test.go
controllers/keycloakrealm/chain/realm_settings.go
controllers/keycloakrealm/chain/realm_settings_test.go
controllers/keycloakrealm/keycloakrealm_controller_integration_test.go
deploy-templates/crds/v1.edp.epam.com_clusterkeycloakrealms.yaml
deploy-templates/crds/v1.edp.epam.com_keycloakrealms.yaml
docs/api.md
pkg/client/keycloak/adapter/gocloak_adapter_realms.go

Add DisplayName to KeycloakRealm/ClusterKeycloakRealm
Fixes #94 
- Integration tests.
- Manual testing.

feat: Add DisplayName to KeycloakRealm/ClusterKeycloakRealm (#94)

---

README.md
bundle/manifests/edp-keycloak-operator.clusterserviceversion.yaml
config/manager/kustomization.yaml
config/manifests/bases/edp-keycloak-operator.clusterserviceversion.yaml
deploy-templates/README.md
deploy-templates/README.md.gotmpl

chore: Update current development version (#102)

---

api/v1/keycloakclient_types.go
config/crd/bases/v1.edp.epam.com_keycloakclients.yaml
config/samples/v1_v1_keycloakclient.yaml
controllers/keycloakclient/chain/chain.go
controllers/keycloakclient/chain/put_client_admin_fine_grained_perms.go
controllers/keycloakclient/chain/put_client_admin_fine_grained_perms_test.go
controllers/keycloakclient/keycloakclient_controller_integration_test.go
deploy-templates/crds/v1.edp.epam.com_keycloakclients.yaml
docs/api.md
pkg/client/keycloak/adapter/gocloak_adapter.go
pkg/client/keycloak/adapter/gocloak_adapter_client.go
pkg/client/keycloak/keycloak_client.go
pkg/client/keycloak/mocks/client_mock.go
pkg/secretref/sourceref_test.go
tests/e2e/helm-success-path/01-install-keycloak-server.yaml
tests/e2e/keycloak-selfsigned-certificates/01-install-keycloak-server.yaml

Adds the ability to enable admin fine grained permissions on Keycloak clients
Fixes #113 

feat: Add Admin Fine Grained Permissions to Keycloak Client

---

controllers/keycloakrealm/chain/user_profile.go
go.mod
go.sum
pkg/client/keycloak/adapter/gocloak_adapter_user.go
tests/e2e/keycloak-selfsigned-certificates/03-assert-keycloak-realm-resource.yaml
tests/e2e/keycloak-selfsigned-certificates/03-install-keycloak-realm-resource.yaml
tests/e2e/keycloak-selfsigned-certificates/99-cleanup.yaml

Add Resty HTTP client to the Keycloak client for user profiles to support self signed certificates in Keycloak
Fixes #128 

fix: Add Resty HTTP client to keycloak_go_client.Client

---

pkg/client/keycloak/adapter/gocloak_adapter_realms.go

The HTML Display name was being set in the realm attributes incorrectly instead of using the existing realm representation field.
Created a realm with a display name. It properly is set via the Keycloak console

fix: Realm HTML Display Name not properly set

---

.github/workflows/e2e.yaml
.github/workflows/pr.yaml

This PR updates the GitHub Actions runner image from ubuntu-20.04 to ubuntu-22.04 across all relevant workflow files.
The change ensures compatibility with the latest Ubuntu environment and takes advantage of security updates, newer packages, and long-term support from GitHub-hosted runners.
Fixes #(#150 )
CI pipelines were triggered automatically for this PR and completed successfully, confirming that workflows continue to function correctly on ubuntu-22.04.
All dependent jobs (e.g., build, lint, e2e tests) executed without errors after the update.

chore: Bump GitHub Actions runner image to 22.04(#150)

---

internal/controller/keycloakclient/chain/service_account.go
internal/controller/keycloakclient/chain/service_account_test.go
internal/controller/keycloakclient/keycloakclient_controller_integration_test.go
pkg/client/keycloak/adapter/gocloak_adapter_service_account.go
pkg/client/keycloak/keycloak_client.go
pkg/client/keycloak/mocks/client_mock.go

For some reason the UpdateUser function isn't properly updating the groups for the service account user.
Reusing the `syncUserGroups` has working locally for me instead.
Fixes #162 

fix: KeycloakClient service account users groups aren't being populated correctly

---

cmd/main.go
internal/controller/helper/controller_helper.go
internal/controller/helper/controller_helper_auth.go
internal/controller/keycloakauthflow/keycloakauthflow_controller.go
internal/controller/keycloakclient/keycloakclient_controller.go
internal/controller/keycloakclient/keycloakclient_controller_integration_test.go
internal/controller/keycloakclientscope/keycloakclientscope_controller.go
internal/controller/keycloakrealmgroup/keycloakrealmgroup_controller.go
internal/controller/keycloakrealmidentityprovider/keycloakrealmidentityprovider_controller.go
internal/controller/keycloakrealmrole/keycloakrealmrole_controller.go
internal/controller/keycloakrealmuser/keycloakrealmuser_controller.go

This PR fixes an issue where deleting a custom resource (e.g., KeycloakClient, KeycloakGroup, etc.) that references a KeycloakRealm CR which has already been deleted results in a permanent reconciliation failure.
Currently, when a child resource is deleted, the controller tries to instantiate a Keycloak client by fetching the corresponding KeycloakRealm CR. If the realm CR has already been deleted, the controller throws a NotFound error, and the resource remains stuck in a terminating state because the finalizer is never removed.
This patch ensures that if the referenced realm no longer exists, the finalizer is still properly removed, allowing the resource to be garbage collected.
Fixes #173 
- [✓ ] Enhancement (non-breaking change which improves an existing feature or documentation)
- …

feat: Allow finalizer cleanup when realm is already deleted

---

api/v1/keycloakrealmuser_types.go
config/crd/bases/v1.edp.epam.com_keycloakrealmusers.yaml
deploy-templates/_crd_examples/keycloakrealmidentityprovider.yaml
deploy-templates/crds/v1.edp.epam.com_keycloakrealmusers.yaml
docs/api.md
pkg/client/keycloak/adapter/gocloak_adapter_user.go
pkg/client/keycloak/adapter/gocloak_adapter_user_test.go

Problem
When assigning a non-existent identity provider, Keycloak returns a 409 Conflict error. This error message is confusing and doesn't indicate that the root cause is a missing identity provider. 
Change
Added explicit identity provider existence validation before attempting to create a user federated identity to prevent confusing 409 Conflict errors and provide more explicit error messages.
Fixes #183 
- Unit test

feat: Add validation for user identity provider

---

api/v1/keycloakclient_types.go
bundle/manifests/edp-keycloak-operator.clusterserviceversion.yaml
config/crd/bases/v1.edp.epam.com_keycloakclients.yaml
config/samples/v1_v1_keycloakrealmidentityprovider.yaml
deploy-templates/Chart.yaml
deploy-templates/_crd_examples/keycloakrealmidentityprovider.yaml
deploy-templates/crds/v1.edp.epam.com_keycloakclients.yaml
docs/api.md
internal/controller/keycloakrealmidentityprovider/keycloakrealmidentityprovider_controller_integration_test.go
tests/e2e/helm-success-path/01-install-keycloak-server.yaml
tests/e2e/helm-success-path/05-assert-identityprovider.yaml
tests/e2e/helm-success-path/05-install-identityprovider.yaml
tests/e2e/keycloak-selfsigned-certificates/01-install-keycloak-server.yaml

- Updated Keycloak version to 26.3  for test cases.
- Tests: changed the alias and providerId from "instagram" to "github" because the "instagram" provider was deprecated and isn't available by default.
- Added a note about the FGAP:V1 for KeycloakClient.Spec.AdminFineGrainedPermissionsEnabled. More details: https://www.keycloak.org/docs/latest/upgrading/index.html#migrating-to-26-2-0
Fixes #192

test: Use Keycloak version 26.3 for tests

---

api/v1/keycloakclient_types.go
api/v1/keycloakrealmuser_types.go
api/v1/zz_generated.deepcopy.go
config/crd/bases/v1.edp.epam.com_keycloakclients.yaml
config/crd/bases/v1.edp.epam.com_keycloakrealmusers.yaml
deploy-templates/crds/v1.edp.epam.com_keycloakclients.yaml
deploy-templates/crds/v1.edp.epam.com_keycloakrealmusers.yaml
docs/api.md
internal/controller/keycloakclient/chain/service_account.go
internal/controller/keycloakclient/chain/service_account_test.go
internal/controller/keycloakclient/keycloakclient_controller.go
internal/controller/keycloakclient/keycloakclient_controller_test.go
internal/controller/keycloakrealmuser/keycloakrealmuser_controller.go
internal/controller/keycloakrealmuser/keycloakrealmuser_controller_integration_test.go
internal/controller/keycloakrealmuser/keycloakrealmuser_test.go
pkg/client/keycloak/adapter/gocloak_adapter_service_account.go
pkg/client/keycloak/adapter/gocloak_adapter_service_account_test.go
pkg/client/keycloak/adapter/gocloak_adapter_user.go
pkg/client/keycloak/adapter/gocloak_adapter_user_test.go
pkg/client/keycloak/keycloak_client.go
pkg/client/keycloak/mocks/client_mock.go
tests/e2e/helm-success-path/03-assert-keycloak-user.yaml
tests/e2e/helm-success-path/03-install-keycloak-user.yaml
tests/e2e/helm-success-path/07-assert-client.yaml
tests/e2e/helm-success-path/07-install-client.yaml

Adds support for multiple values for a user attribute as well as backwards compatibility with the old string value
Fixes #194

feat: Add support for list of attributes with the same key

---

internal/controller/keycloakrealmidentityprovider/chain/put_client_admin_fine_grained_perms.go
internal/controller/keycloakrealmidentityprovider/chain/put_client_admin_fine_grained_perms_test.go
pkg/client/keycloak/adapter/identity_provider.go

When adding policies to a KeycloakRealmIdentityProvider it is not added to the scope permission. The controller was using the alias instead of the internalID of the IDP for the permission name
Fixes #216 
Tested on deployed EKS cluster

fix: KeycloakRealmIdentityProvider policies not being added to permissions

---

config/manifests/bases/edp-keycloak-operator.clusterserviceversion.yaml
config/manifests/kustomization.yaml
docs/development.md

Automatically set containerImage annotation in the operator bundle ClusterServiceVersion using kustomize replacements when running `make bundle`.

chore: Generate containerImage annotation for ClusterServiceVersion
